
package com.example.backend.service.impl.controllerWS.personnelService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonnelServiceSoap", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonnelServiceSoap {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "idAuthentication", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.personnelService.IdAuthentication")
    @ResponseWrapper(localName = "idAuthenticationResponse", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.personnelService.IdAuthenticationResponse")
    @Action(input = "http://Service/PersonnelServiceSoap/idAuthenticationRequest", output = "http://Service/PersonnelServiceSoap/idAuthenticationResponse")
    public String idAuthentication(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.backend.service.impl.controllerWS.personnelService.PersonnelEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStaffInfoById", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.personnelService.GetStaffInfoById")
    @ResponseWrapper(localName = "getStaffInfoByIdResponse", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.personnelService.GetStaffInfoByIdResponse")
    @Action(input = "http://Service/PersonnelServiceSoap/getStaffInfoByIdRequest", output = "http://Service/PersonnelServiceSoap/getStaffInfoByIdResponse")
    public PersonnelEntity getStaffInfoById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
