
package com.example.backend.service.impl.controllerWS.personnelService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonnelService", targetNamespace = "http://impl.Service/", wsdlLocation = "http://localhost:8080/PersonnelService?wsdl")
public class PersonnelService
    extends Service
{

    private final static URL PERSONNELSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONNELSERVICE_EXCEPTION;
    private final static QName PERSONNELSERVICE_QNAME = new QName("http://impl.Service/", "PersonnelService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PersonnelService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONNELSERVICE_WSDL_LOCATION = url;
        PERSONNELSERVICE_EXCEPTION = e;
    }

    public PersonnelService() {
        super(__getWsdlLocation(), PERSONNELSERVICE_QNAME);
    }

    public PersonnelService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONNELSERVICE_QNAME, features);
    }

    public PersonnelService(URL wsdlLocation) {
        super(wsdlLocation, PERSONNELSERVICE_QNAME);
    }

    public PersonnelService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONNELSERVICE_QNAME, features);
    }

    public PersonnelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonnelService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonnelServiceSoap
     */
    @WebEndpoint(name = "PersonnelServiceSoapPort")
    public PersonnelServiceSoap getPersonnelServiceSoapPort() {
        return super.getPort(new QName("http://impl.Service/", "PersonnelServiceSoapPort"), PersonnelServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonnelServiceSoap
     */
    @WebEndpoint(name = "PersonnelServiceSoapPort")
    public PersonnelServiceSoap getPersonnelServiceSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.Service/", "PersonnelServiceSoapPort"), PersonnelServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONNELSERVICE_EXCEPTION!= null) {
            throw PERSONNELSERVICE_EXCEPTION;
        }
        return PERSONNELSERVICE_WSDL_LOCATION;
    }

}
