
package com.example.backend.service.impl.controllerWS.erpService;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ERPServiceSoap", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ERPServiceSoap {


    /**
     * 
     * @return
     *     returns java.util.List<com.example.backend.service.impl.controllerWS.erpService.LineEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLineResources", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.erpService.GetAllLineResources")
    @ResponseWrapper(localName = "getAllLineResourcesResponse", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.erpService.GetAllLineResourcesResponse")
    @Action(input = "http://Service/ERPServiceSoap/getAllLineResourcesRequest", output = "http://Service/ERPServiceSoap/getAllLineResourcesResponse")
    public List<LineEntity> getAllLineResources();

    /**
     * 
     * @return
     *     returns java.util.List<com.example.backend.service.impl.controllerWS.erpService.ResourceEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResourceTeamInfo", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.erpService.GetResourceTeamInfo")
    @ResponseWrapper(localName = "getResourceTeamInfoResponse", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.erpService.GetResourceTeamInfoResponse")
    @Action(input = "http://Service/ERPServiceSoap/getResourceTeamInfoRequest", output = "http://Service/ERPServiceSoap/getResourceTeamInfoResponse")
    public List<ResourceEntity> getResourceTeamInfo();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.backend.service.impl.controllerWS.erpService.LineEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLineResourceById", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.erpService.GetLineResourceById")
    @ResponseWrapper(localName = "getLineResourceByIdResponse", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.erpService.GetLineResourceByIdResponse")
    @Action(input = "http://Service/ERPServiceSoap/getLineResourceByIdRequest", output = "http://Service/ERPServiceSoap/getLineResourceByIdResponse")
    public LineEntity getLineResourceById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.backend.service.impl.controllerWS.erpService.MaterialEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMaterialInfoById", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.erpService.GetMaterialInfoById")
    @ResponseWrapper(localName = "getMaterialInfoByIdResponse", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.erpService.GetMaterialInfoByIdResponse")
    @Action(input = "http://Service/ERPServiceSoap/getMaterialInfoByIdRequest", output = "http://Service/ERPServiceSoap/getMaterialInfoByIdResponse")
    public MaterialEntity getMaterialInfoById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.example.backend.service.impl.controllerWS.erpService.BomEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBOMs", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.erpService.GetAllBOMs")
    @ResponseWrapper(localName = "getAllBOMsResponse", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.erpService.GetAllBOMsResponse")
    @Action(input = "http://Service/ERPServiceSoap/getAllBOMsRequest", output = "http://Service/ERPServiceSoap/getAllBOMsResponse")
    public List<BomEntity> getAllBOMs();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.backend.service.impl.controllerWS.erpService.BomEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBOMById", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.erpService.GetBOMById")
    @ResponseWrapper(localName = "getBOMByIdResponse", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.erpService.GetBOMByIdResponse")
    @Action(input = "http://Service/ERPServiceSoap/getBOMByIdRequest", output = "http://Service/ERPServiceSoap/getBOMByIdResponse")
    public BomEntity getBOMById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
