
package com.example.backend.service.impl.controllerWS.erpService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ERPService", targetNamespace = "http://impl.Service/", wsdlLocation = "http://localhost:8080/ERPService?wsdl")
public class ERPService
    extends Service
{

    private final static URL ERPSERVICE_WSDL_LOCATION;
    private final static WebServiceException ERPSERVICE_EXCEPTION;
    private final static QName ERPSERVICE_QNAME = new QName("http://impl.Service/", "ERPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ERPService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ERPSERVICE_WSDL_LOCATION = url;
        ERPSERVICE_EXCEPTION = e;
    }

    public ERPService() {
        super(__getWsdlLocation(), ERPSERVICE_QNAME);
    }

    public ERPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ERPSERVICE_QNAME, features);
    }

    public ERPService(URL wsdlLocation) {
        super(wsdlLocation, ERPSERVICE_QNAME);
    }

    public ERPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ERPSERVICE_QNAME, features);
    }

    public ERPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ERPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ERPServiceSoap
     */
    @WebEndpoint(name = "ERPServiceSoapPort")
    public ERPServiceSoap getERPServiceSoapPort() {
        return super.getPort(new QName("http://impl.Service/", "ERPServiceSoapPort"), ERPServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ERPServiceSoap
     */
    @WebEndpoint(name = "ERPServiceSoapPort")
    public ERPServiceSoap getERPServiceSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.Service/", "ERPServiceSoapPort"), ERPServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ERPSERVICE_EXCEPTION!= null) {
            throw ERPSERVICE_EXCEPTION;
        }
        return ERPSERVICE_WSDL_LOCATION;
    }

}
