
package com.example.backend.service.impl.controllerWS.orderService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderServiceSoap", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderServiceSoap {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.backend.service.impl.controllerWS.orderService.OrderEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderInfoById", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.orderService.GetOrderInfoById")
    @ResponseWrapper(localName = "getOrderInfoByIdResponse", targetNamespace = "http://Service/", className = "com.example.backend.service.impl.controllerWS.orderService.GetOrderInfoByIdResponse")
    @Action(input = "http://Service/OrderServiceSoap/getOrderInfoByIdRequest", output = "http://Service/OrderServiceSoap/getOrderInfoByIdResponse")
    public OrderEntity getOrderInfoById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
