INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (1, 'DAY', '5', '5组-童玲 (5)', 5);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (2, 'NIGHT', '6', '6组-李  倩（4）', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (3, 'DAY', '7', '7组-黄娣（4）', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (4, 'DAY', '8', '8组-张萍（4）', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (5, 'DAY', '14', '14组-周  清（4）', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (6, 'NIGHT', '16', '16组-朱美（4）', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (7, 'DAY', '4', '4组-赵勤（3）', 3);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (8, 'NIGHT', '2', '2组-丁梅（3）', 3);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (9, 'DAY', '39', '39组-刘  霞（3）', 3);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (10, 'NIGHT', '23', '23组-吴凤（4）', 3);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (11, 'DAY', '24', '24组-张 娟1（3）', 3);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (12, 'DAY', '13', '13组-刘燕（3）', 3);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (13, 'NIGHT', '20', '20组-王梅（4）', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (14, 'DAY', '11', '11组-张  娟（4）', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (15, 'NIGHT', '28', '28组-杜珍(4)', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (16, 'DAY', '9', '9组-张敏（5）', 5);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (17, 'DAY', '10', '10组-陈  云（5）', 5);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (18, 'NIGHT', '1', '1组-彭慧 (5)', 5);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (19, 'NIGHT', '12', '12组-姚兰（5）', 5);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (20, 'NIGHT', '15', '15组-李娟（5）', 5);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (21, 'DAY', '40', '40组-高燕（5）', 5);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (22, 'DAY', '27', '27组-徐燕(5)', 5);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (23, 'DAY', '26', '26组-杨  丽（5）', 5);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (24, 'DAY', '3', '3组-李翠 (4)', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (25, 'NIGHT', '18', '18组-芮  娜（3）', 3);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (26, 'NIGHT', '19', '19组-王  秀（3）', 3);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (27, 'DAY', '21', '21组-陈花（4）', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (28, 'DAY', '17', '17组-吴凤（4）', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (29, 'DAY', '36', '36组-谢霞(4)', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (30, 'NIGHT', '30', '30组-陈  梅(4)', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (31, 'NIGHT', '31', '31组-史玲(4)', 4);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (32, 'DAY', '33', '33组-许萍（5）', 5);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (33, 'DAY', '22', '22组-陈霞（3）', 3);
INSERT INTO web_plus.group_po (id, class_name, group_id, group_name, member_count) VALUES (34, 'DAY', '0', 'UKK组-王娣（6）', 6);